# Generated by Django 6.0.3 on 2026-04-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='code_snippet_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='code_snippet_end_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='code_snippet_start_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
