# Generated by Django 6.0.3 on 2026-03-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatroom_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='members',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='project',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
