# Generated by Django 6.0.3 on 2026-04-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_chatroom_members_remove_chatroom_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecomment',
            name='comment_type',
            field=models.CharField(choices=[('file', 'Whole File'), ('line', 'Line Range')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='end_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='start_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
