# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_codefile_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='codefile',
            name='is_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codefile',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
